# Generated by Django 5.0.6 on 2024-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
