# Generated by Django 5.0.6 on 2024-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_alter_employee_emp_code_alter_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
    ]
